import type { Metadata } from "next";
import "./globals.css";
import FontProvider from "./FontProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <FontProvider>{children}</FontProvider>
      </body>
    </html>
  );
}
